name: Learning GitHub Actions Workflow
run-name: Manual run by @${{ github.actor }} (#${{ github.run_number }})
#on: [push]
on: 
  workflow_dispatch:
    inputs:
      run_now:
        description: 'Run the python code workflow now'
        required: true
        default: 'yes'
        type: choice
        options: ['yes', 'no']
      run_curl:
        description: 'Run the curl command'
        required: false
        type: choice
        default: 'no'
        options: ['yes', 'no']
  
jobs:
  Basics:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered by
        run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Say what OS
        run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Basic terminal commands
        run: ls -lah
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name:
        run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}

  Available-Python-Info:
    runs-on: ubuntu-latest
    needs: Basics
    steps:
      - name: Check Python Version
        run: python --version
      - name: Check Pip Version
        run: pip --version
      - name: List Installed Packages
        run: pip list
      - name: Install Requests Package
        run: pip install requests
      - name: Verify Requests Installation
        run: pip show requests

  Access-Workflow-Variables:
    needs: Available-Python-Info
    runs-on: ubuntu-latest
    steps:
      - name: Accessing Global Workflow Variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
      - name: Display workflow inputs âš™ï¸
        run: |
          echo "Value for 'run_now': ${{ github.event.inputs.run_now }}"
          echo "Value for 'dont_run': ${{ github.event.inputs.dont_run }}"

  Run-My-Code:
    runs-on: ubuntu-latest
    needs: Access-Workflow-Variables
    if: ${{ github.event.inputs.run_now == 'yes' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python and uv cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv âš¡ï¸
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install dependencies with uv
        run: uv pip install . --system
      - name: List Installed Dependencies ðŸ“¦
        run: uv pip list
      - name: Run Python script
        run: python main.py

  Run-Curl-Command:
    runs-on: ubuntu-latest
    needs: Basics
    if: ${{ github.event.inputs.run_curl == 'yes' }}
    steps:
      - name: Run curl on GitHub API
        run: |
          echo "Running a curl command..."
          curl -I https://api.github.com