name: Github Actions Workflow
on: [push]
jobs:
  Basics:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered by
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Say what OS
        run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Basic terminal commands
        run: ls -lah
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name:
        run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
  Available-Python-Info:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python Version
        run: python --version
      - name: Check Pip Version
        run: pip --version
      - name: List Installed Packages
        run: pip list
      - name: Install Requests Package
        run: pip install requests
      - name: Verify Requests Installation
        run: pip show requests
