name: Github Actions Workflow
#on: [push]
on: 
  workflow_dispatch:
    inputs:
      run_now:
        description: 'Run the workflow now'
        required: true
        default: 'yes'
        options:
          - 'yes'
          - 'no'
      dont_run:
        description: 'Do not run the workflow'
        required: false
        default: 'no'
        options:
          - 'no'
          - 'yes'
  
jobs:
  Basics:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered by
        run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Say what OS
        run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Basic terminal commands
        run: ls -lah
      - name: Checkout the repository
        uses: actions/checkout@v5
      - name:
        run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
  Available-Python-Info:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python Version
        run: python --version
      - name: Check Pip Version
        run: pip --version
      - name: List Installed Packages
        run: pip list
      - name: Install Requests Package
        run: pip install requests
      - name: Verify Requests Installation
        run: pip show requests
